idf_component_register(
    SRCS
        "hello_world_main.c"
        "wifi_manager.c"
        "mqtt_manager.c"
        "cloud_event_service.c"
        "manual_sos.c"
        "buzzer_output.c"
    INCLUDE_DIRS "."
    REQUIRES
        driver
        esp_timer
        esp_hw_support
        esp_wifi
        esp_event
        esp_netif
        nvs_flash
        mqtt
        mbedtls
        esp_http_client
        json
)
